webapp/config/routes.rb
Webapp::Application.routes.draw do
  root to: "map#index"

  match "/universities/*id", to: "universities#show", constraints: { :format => /(html|xml|json)/ }
  resources :universities, only: [:index, :show]

  match "/people/*id", to: "people#show", constraints: { :format => /(html|xml|json)/ }
  resources :people, only: [:index, :show]

  match "/movies/*id", to: "movies#show", constraints: { :format => /(html|xml|json)/ }
  resources :movies, only: [:index, :show]
end

webapp/app/models/university.rb
require "sparql/client"

class University
  ENDPOINT = "http://localhost:2020/sparql"

  PREFIXES = <<-EOP
    prefix vocab: <http://semweb.moretea.nl/vocab/> 
    prefix rankings_vocab: <http://semweb.moretea.nl/university_rankings/> 
    prefix rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#> 
    prefix rdfs: <http://www.w3.org/2000/01/rdf-schema#> 
    prefix xsd: <http://www.w3.org/2001/XMLSchema#> 
    prefix owl: <http://www.w3.org/2002/07/owl#> 
  EOP

  attr_accessor :attributes
  
  def initialize(url)
    @url = url
    @attributes = {}
  end

  def id
    @url
  end

  def to_param
    CGI.escape(@url)
  end

  def method_missing key, *args, &block
    if ATTRIBUTES.keys.member? key
      @attributes[key]
    else
      super
    end
  end

  ATTRIBUTES = { 
      geo_lat:  "http://www.w3.org/2003/01/geo/wgs84_pos#lat",
      geo_long: "http://www.w3.org/2003/01/geo/wgs84_pos#long",
      label: "http://www.w3.org/2000/01/rdf-schema#label",
      nr_students: "http://dbpedia.org/property/students"
  }

  ATTR_INV = ATTRIBUTES.invert

  class << self
    def type_name
      "rankings_vocab:University"
    end

    def search q
      match = <<-SPARQL
        {
          ?match rdf:type #{self.type_name} .
          ?match rdfs:label ?label .
          FILTER REGEX(str(?label), "#{q}", "i")
        }
      SPARQL

      attribute_parts = []
      search_attributes =  ATTRIBUTES.reject { |k, v| k == :label}
      search_attributes.values.each_with_index do |attr, idx| 
        attribute_parts << <<-SPARQL
          {
            ?match ?p#{idx} ?o#{idx} .
            FILTER(?p#{idx} = <#{attr}>)
          }
        SPARQL
      end 

      parts = [match] + attribute_parts
      query_results = query <<-QUERY
        SELECT *
        WHERE {
          #{parts.join("OPTIONAL")}
        }
      QUERY

      results = {}

      query_results.each do |result|
        # Find objects
        object = results[result.match.to_s] ||= self.new(result.match.to_s)
        object.attributes[:label] = result.label

        search_attributes.each_with_index do |attr, idx|
          # If set, set relation
          pred_key = "p#{idx}".to_sym
          if result[pred_key]
            p = result[pred_key].to_s
            obj_key = "o#{idx}".to_sym
            object.attributes[ATTR_INV[p] || p] = decode(result[obj_key])
          end
        end
      end

      results.values
    end

    def find url
      match = <<-SPARQL
        {
          ?match rdf:type #{self.type_name} .
          FILTER(?match = <#{url}>)
        }
      SPARQL

      attribute_parts = []
      ATTRIBUTES.values.each_with_index do |attr, idx| 
        attribute_parts << <<-SPARQL
          {
            ?match ?p#{idx} ?o#{idx} .
            FILTER(?p#{idx} = <#{attr}>)
          }
        SPARQL
      end 

      parts = [match] + attribute_parts
      result = query <<-QUERY
        SELECT *
        WHERE {
          #{parts.join("OPTIONAL")}
        }
      QUERY

      decorate(result, type: self.type_name).first
    end

    def all
      match = <<-SPARQL
        {
          ?match rdf:type #{self.type_name} .
        }
      SPARQL

      attribute_parts = []
      ATTRIBUTES.values.each_with_index do |attr, idx| 
        attribute_parts << <<-SPARQL
          {
            ?match ?p#{idx} ?o#{idx} .
            FILTER(?p#{idx} = <#{attr}>)
          }
        SPARQL
      end 

      parts = [match] + attribute_parts
      result = query <<-QUERY
        SELECT *
        WHERE {
          #{parts.join("OPTIONAL")}
        }
      QUERY

      decorate(result, type: self.type_name)
    end

    protected

    def query q
      sparql_query = PREFIXES + "\n" + q 

      Rails.logger.debug sparql_query
      client.query(sparql_query)
    end

    def decorate query_results, type
      results = {}

      query_results.each do |result|
        # Find objects
        object = results[result.match.to_s] ||= self.new(result.match.to_s)

        ATTRIBUTES.each_with_index do |attr, idx|
          # If set, set relation
          pred_key = "p#{idx}".to_sym
          if result[pred_key]
            p = result[pred_key].to_s
            obj_key = "o#{idx}".to_sym
            object.attributes[ATTR_INV[p] || p] = decode(result[obj_key])
          end
        end
      end

      results.values
    end

    DECODE_DATATYPES = {
      "http://www.w3.org/2001/XMLSchema#float" => lambda { |val| val.to_s.to_f },
      "" => lambda { |val| val.value } # string
    }
    def decode(thing)
      if thing.kind_of? RDF::Literal
        type = thing.datatype.to_s
        method = DECODE_DATATYPES[type]
        debugger if method.nil?
        raise "Unkown datatype datatype:#{type} thing:#{thing.inspect}" if method.nil?
        method.call(thing)
      else
        thing
      end
    end

    def client
      SPARQL::Client.new(ENDPOINT)
    end
  end
end

webapp/app/controllers/universities_controller.rb
class UniversitiesController < ApplicationController
  def index
    if params[:q]
      @universities = University.search params[:q]
    else
      @universities = University.all
    end

    if params[:replace] == 'true'
      render partial: "universities/university_list_items"
    end
  end

  def show
    id = CGI.unescape(params[:id])
    @university = University.find(id)
    @people = Person.with_alma_mater(id)
  end
end

webapp/app/views/universities/_university_list_items.haml
- @universities.each do |university|
  - next if university.label.nil?
  %li= link_to(university.label || "Unkown; id:" + university.id, university_path(university))

webapp/app/views/universities/index.haml
.span8
  %h1 All universities
  %ul#university_list
    = render partial: "university_list_items"
.span4
  %h2 Search
  %form
    %input{id: "searchField", type: :search, placeholder: "name of university"}

:javascript
  $(function() {
    $("#searchField").on("keydown", _.debounce(function () {
      var query = $("#searchField").val();
      $("#university_list").load('/universities?replace=true&q=' + escape(query));
    }, 500));
  });

webapp/app/views/universities/index.js.haml
= render partial: "university_list_items"

webapp/app/views/universities/show.haml
- content_for(:title, @university.label)
.span12{about: @university.id}
  %p{property: "http://dbpedia.org/property/students", content: @university.nr_students} Number of students: #{@university.nr_students}
  - if @university.geo_lat && @university.geo_long
    %h2 Location
    #map_div
    :javascript
      google.load("visualization", "1", {packages:["map"]});
      google.setOnLoadCallback(drawMap);
      function drawMap() {
        var data = google.visualization.arrayToDataTable([
          ['Lat', 'Lon', 'Name'],
          [#{@university.geo_lat}, #{@university.geo_long}, '#{@university.label}'],
        ]);

        var map = new google.visualization.Map(document.getElementById('map_div'));
        map.draw(data, {showTip: true});
      }
  %h2 People who studied hier
  %ul
    - @people.each do |person|
      %li= link_to(person.full_name, person_url(person))