webapp/config/routes.rb
Webapp::Application.routes.draw do
  root to: "map#index"

  match "/universities/*id", to: "universities#show", constraints: { :format => /(html|xml|json)/ }
  resources :universities, only: [:index, :show]

  match "/people/*id", to: "people#show", constraints: { :format => /(html|xml|json)/ }
  resources :people, only: [:index, :show]

  match "/movies/*id", to: "movies#show", constraints: { :format => /(html|xml|json)/ }
  resources :movies, only: [:index, :show]
end

webapp/app/controllers/movies_controller.rb
class MoviesController < ApplicationController
  def index
    if params[:q]
      @movies = Movie.search params[:q]
    else
      @movies = Movie.all
    end

    if params[:replace] == 'true'
      render partial: "movies/movie_list_items"
    end
  end

  def show
    id = CGI.unescape(params[:id])
    @movie = Movie.find(id)

   # @people = @movie.participants.collect do |url|
   #   Person.find(url)
   # end
    #
   @people = Person.all[10..20]
  end
end

webapp/app/views/movies/_movie_list_items.haml
- @movies.each do |movie|
  - movie_url = movie_path(CGI.escape(movie.id))
  %li
    = link_to(movie.title, movie_url)

webapp/app/views/movies/index.haml
.span8
  %h1 All movies
  %ul#movie_list
    = render partial: "movie_list_items"
.span4
  %h2 Search
  %form
    %input{id: "searchField", type: :search, placeholder: "name of movie"}

:javascript
  $(function() {
    $("#searchField").on("keydown", _.debounce(function () {
      var query = $("#searchField").val();
      $("#movie_list").load('/movies?replace=true&q=' + escape(query));
    }, 500));
  });

webapp/app/views/movies/show.haml
- content_for(:title, @movie.title)
.span12{about: @movie.id}
  %h2 Trailer
  %iframe{property:"vocab:youtubeTrailer", content: @movie.youtube_id, src:"http://www.youtube.com/embed/#{@movie.youtube_id}", width:640, height:480, frameborder:0}
  %h2 People (TODO)
  %ul
    - @people.each do |person|
      %li= link_to(person.full_name, person_path(person))