webapp/config/routes.rb
Webapp::Application.routes.draw do
  root to: "map#index"

  match "/universities/*id", to: "universities#show", constraints: { :format => /(html|xml|json)/ }
  resources :universities, only: [:index, :show]

  match "/people/*id", to: "people#show", constraints: { :format => /(html|xml|json)/ }
  resources :people, only: [:index, :show]

  match "/movies/*id", to: "movies#show", constraints: { :format => /(html|xml|json)/ }
  resources :movies, only: [:index, :show]
end

webapp/app/views/layouts/application.haml
!!!
%html{prefix: ApplicationController::PREFIXES}

%head
  %title SemanticWeb
  = stylesheet_link_tag    "application", :media => "all"
  = javascript_include_tag "application"

  %script{type:"text/javascript", src:"https://www.google.com/jsapi"}
  %script{type:"text/javascript", id:"sgvzlr_script", src:"http://sgvizler.googlecode.com/svn/release/0.5/sgvizler.js"}
  = javascript_include_tag "sgvizler_config"

  = csrf_meta_tags
  = yield :head

%body{class: "#{params[:controller].gsub("/","_")}_controller #{params[:action]}_action"}
  .navbar.navbar-fixed-top
    .navbar-inner
      .container
        %a.brand{:href => "/"} UniMovies
        %ul.nav
          %li.divider-vertical
          %li= link_to 'Map', root_path
          %li.divider-vertical
          %li= link_to 'Universities', universities_path
          %li.divider-vertical
          %li= link_to 'People', people_path
          %li.divider-vertical
          %li= link_to 'Movies', movies_path
          %li.divider-vertical
  .container
    .content
      %h1
        = yield :title
      .row
        = yield